pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                dir('application') {

                    sh 'docker build -t mon_app_flask .'
            }
        }
        
        stage('Deploy') {
            steps {
                // Utilisez kubectl pour déployer sur Kubernetes
                sh 'kubectl apply -f deployment.yaml'
            }
        }
    }
}
