apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-flask
  template:
    metadata:
      labels:
        app: app-flask
    spec:
      containers:
      - name: app-flask
        image: app_flask:latest
        ports:
        - containerPort: 5000
