- hosts: localhost
  become: yes
  tasks:
  - name: Installer Docker
    shell: |
      dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      dnf install -y docker-ce docker-ce-cli containerd.io
      systemctl start docker
      systemctl enable docker
