- hosts: localhost
  become: yes
  tasks:
  - name: Ajouter le dépôt Jenkins
    get_url:
      url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo
      mode: '0644'

  - name: Importer la clé GPG Jenkins
    rpm_key:
      state: present
      key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

  - name: Installer Jenkins
    yum:
      name: jenkins
      state: latest

  - name: Démarrer et activer Jenkins
    systemd:
      name: jenkins
      state: started
      enabled: yes
